name: Infrastructure Deployment

on:
  push:
    branches: [main, staging]
    paths: 
      - 'terraform/**'
      - '.github/workflows/infrastructure-deploy.yml'
  pull_request:
    branches: [destoy-tf]
    paths: ['terraform/**']
  workflow_dispatch:

env:
  TF_VAR_region: ${{ vars.AWS_REGION }}
  TF_VAR_project_name: ${{ vars.PROJECT_NAME }}
  TF_VAR_availability_zones: ${{ vars.AWS_AVAILABILITY_ZONE }}
  TF_VAR_public_subnet_cidrs: ${{ vars.AWS_PUBLIC_SUBNET_CIDRS }}
  TF_VAR_private_subnet_cidrs: ${{ vars.AWS_PRIVATE_SUBNET_CIDRS }}
  TF_VAR_instance_type: ${{ vars.AWS_ASG_INSTANCE_TYPE }}
  TF_VAR_desired_capacity: ${{ vars.AWS_ASG_DESIRED_CAPACITY }}
  TF_VAR_max_size: ${{ vars.AWS_ASG_MAX_SIZE }}
  TF_VAR_min_size: ${{ vars.AWS_ASG_MIN_SIZE }}
  TF_VAR_redis_engine_version: ${{ vars.AWS_REDIS_ENGINE_VERSION }}
  TF_VAR_redis_node_type: ${{ vars.AWS_REDIS_NODE_TYPE }}
  TF_VAR_redis_num_node_grps: ${{ vars.AWS_REDIS_NUM_NODE_GRPS }}
  TF_VAR_redis_replicas_per_node_grp: ${{ vars.AWS_REDIS_REPLICAS_PER_NODE_GRPS }}
  TF_VAR_redis_snapshot_retention_limit: ${{ vars.AWS_REDIS_SNAPSHOT_RETENTION_LIMIT }}
  TF_VAR_redis_snapshot_window: ${{ vars.AWS_REDIS_SNAPSHOT_WINDOW }}
  TF_VAR_redis_maintenance_window: ${{ vars.AWS_REDIS_MAINTENANCE_WINDOW }}
  TF_VAR_redis_cloudwatch_retention_in_days: ${{ vars.AWS_REDIS_CLOUDWATCH_RETENTION_DAYS }}
  TF_VAR_ecr_image_retention_count: ${{ vars.AWS_ECR_IMAGE_RETENTION_COUNT }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        id: plan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan


  terraform-apply:
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      # - name: Terraform Apply
      #   run: terraform apply tfplan

      # - name: Output Terraform Data
      #   run: terraform output -json > outputs.json

      # - name: Update GitHub Secrets
      #   run: |
      #     python3 scripts/update_env_vars.py


  terraform-destroy:
    if: github.base_ref == 'destoy-tf' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve 
